### ISSUE TITLE
Is there room to display the Description of the CustomFilter selected in FilterParams?

### ISSUE THREAD

**Issue by emyoulation** [kkujansuu/gramps#14]

**Comment by kkujansuu** [comment]
I have added the filter descriptions (comments) in the display. I also replaced the rule class names (e.g. HasIdOf) with the rule name and description (e.g. "Person with <id>" / "Matches person with a specified Gramps ID". Change is in version 1.1.0

**Comment by emyoulation** [comment]
works in v.1.1.0 version. (thank you) 

Please close
