### ISSUE TITLE
some time the display is wrong

### ISSUE THREAD

**Issue by HelgeGitHub** [kkujansuu/gramps#18]
Using Gramps 5.1.3 in Windows (GrampsAIO64 5.1.3) the display changes wrong, see attached file.
![Screenshot 2022-09-17 114828](https://user-images.githubusercontent.com/3822386/190872707-67861283-2638-446b-8d06-1a726372cd2f.png)

**Comment by emyoulation** [comment]
Helge, 

Are you talking about the fill colors being too dark to see the text?  

Those color choices were submitted as a patch and a tradeoff for visibility problems using dark mode themes.

You can try a [newly submitted suggestion](https://github.com/kkujansuu/gramps/issues/9#issuecomment-1249744238) with colors that improve visibility for both light AND dark themes.

If this was not the "display is wrong" issue, please describe your problem in more detail.

**Comment by HelgeGitHub** [comment]
No, the color isn't the issue. If you look at the pictures, you should see the
wrong display beside the colors: the left part tends to be to small because
the button part is to wide.

Nevertheless I'll try the new version soon.

Helge


Am 22.09.2022 um 21:58 schrieb Emyoulation or BAMaustin
***@***.***>:



Helge,

Are you talking about the fill colors being too dark to see the text?

Those color choices were submitted as a patch and a tradeoff for visibility
problems using dark mode themes.

You can try a newly submitted suggestion with colors that improve visibility
for both light AND dark themes.

If this was not the "display is wrong" issue, please describe your problem in
more detail.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by emyoulation** [comment]
@HelgeGitHub  Hopefully you have had time to check the newer version?

I have not seen the behavior with all the extra space on the right.  However, The window seems to be designed to resize dynamically as the selected filter changes.  And when the horizontal size is manually changed, the content simply re-centers.
![image](https://user-images.githubusercontent.com/69127217/193409190-8021902c-915f-4cfc-a28a-c66400b73cef.png)
 
![image](https://user-images.githubusercontent.com/69127217/193409235-ed8a8ffb-0652-444d-b0d2-12233845c94d.png)

And "dark mode" ; 
![image](https://user-images.githubusercontent.com/69127217/193409342-4a650fa7-aae4-4cb7-bc1a-13ed05f11f35.png)

**Comment by HelgeGitHub** [comment]
I can't reproduce it any more. Please close the issue.

**Comment by HelgeGitHub** [comment]
I used the wrong button, sorry.

**Comment by kkujansuu** [comment]
This problem seemed to occur if there were no filters in a category or the filter display was too narrow. There is a fix in version 1.1.0, let me know if that does not help.
