### ISSUE TITLE
Layering and multiple instancing of FilterParams dialog

### ISSUE THREAD

**Issue by emyoulation** [kkujansuu/gramps#19]
* Unlike the SuperTool, the dialog is not added to the "Windows" menu when spawned
* Multiple instances of FilterParams are possible
* The FilterParams dialog may be layered under other Gramps windows but SHOULD be on top of anything except the Progress dialog it can spawn or a spawned modal Error dialog

**Comment by kkujansuu** [comment]
I thought these were already fixed in the latest version (December 2021).

**Comment by emyoulation** [comment]
I recently downloaded it again and tweaked the RGBa colors to the ones with alpha transparencies.  
It is the version where the parent application isn't set for the FilterParams, the titlebar mis-reads as "gramps.exe" and doesn't show in the Gramps' Windows menu.

-Brian 
 
  On Tue, Oct 4, 2022 at 3:58, ***@***.***> wrote:   


I thought these were already fixed in the latest version (December 2021).

**Comment by emyoulation** [comment]
works in v.1.1.0 version. (thank you) 

Please close
