### ISSUE TITLE
Edit --> OK: the filter selection jumps to the first filter in the list

### ISSUE THREAD

**Issue by HelgeGitHub** [kkujansuu/gramps#20]
If one edits a filter and closes the dialogue "Define Filter" with OK, the dialogue "Filter Parameters" set the focus to the first Filter of the filter list - instead to stay at the same filter as before the edit action.

Cancel works well.

**Comment by kkujansuu** [comment]
Should be fixed in the new version 1.1.0.

**Comment by HelgeGitHub** [comment]
confirmed, issue may be closed
