### ISSUE TITLE
Filters with user selectable parameter ("Select..." action) loose there values by Cancel

### ISSUE THREAD

**Issue by HelgeGitHub** [kkujansuu/gramps#21]
If one uses the "Select..." button here
![Screenshot 2022-10-01 161338](https://user-images.githubusercontent.com/3822386/193413696-26759eef-0e05-4f9b-b3af-e6e082d25d60.png)
an decide to cancel these action by the Cancel button of the selection dialogue (the "Select Person" in this example) the main dialogue looses the parameter
 
![Screenshot 2022-10-01 161845](https://user-images.githubusercontent.com/3822386/193413920-6c619c0f-919a-4cc3-9f0f-1bf58d4c46be.png)

**Comment by kkujansuu** [comment]
Yes, that is true. But the same issue seems to be in the regular filter editor. FilterParams calls the same code within Gramps as the regular filter editor. So the fix should probably go there. I think I will not attempt to fix this in FilterParams.

**Comment by HelgeGitHub** [comment]
You are right, I have to file a Gramps issue
