### ISSUE TITLE
Test runs from FilterParams have windows menu items that are undefined

### ISSUE THREAD

**Issue by emyoulation** [kkujansuu/gramps#24]
A test run from FilterParams created a window that wasn't at the top layer and has a bad label in the Windows menu. Listed as  "Windows : FilterParams : Undefined Submenu : Undefined Menu..."
![image](https://user-images.githubusercontent.com/69127217/194392352-0ad2a7bf-9097-4d4b-9b17-a5d0a83bb944.png)

The generated window has good data and are showing a proper title "Filter Test - Gramps"

**Comment by kkujansuu** [comment]
Fixed in 1.1.2.
