### ISSUE TITLE
proposed Layout glade file for FilterParams

### ISSUE THREAD

**Issue by emyoulation** [kkujansuu/gramps#26]
The elements of the dialog were butted up against each other, losing the edges. Installed Glade and experimented a bit.  (Sure is a pain without knowing which container is which!)

Attached is a ZIP with a proposed `filterparams.glade` file.

It has a lot of padding changes, a re-ordering of the Buttons to put feature in an order that makes sense (and puts a little distance between the "Delete" button and "Save" button ... or the "X" close gadget.) It feels less crowded.

(By the way, the fixed-width scrollbars didn't appear until they were turned off and back on in the Preferences added-on Theme tab.)

screen capture with tweaked Glade
![image](https://user-images.githubusercontent.com/69127217/194684400-19ba0ff6-40ac-4d80-94e4-ccbc7f656675.png) 

screen capture with Original Glade
![image](https://user-images.githubusercontent.com/69127217/194684552-5c20c2eb-2d2e-46c5-943e-051c63684a71.png)

Here's the zip containing the glade file:
[filterparams.zip](https://github.com/kkujansuu/gramps/files/9738270/filterparams.zip)

**Comment by emyoulation** [comment]
the submitted Glade file also has an added tooltip for the  Delete button

**Comment by kkujansuu** [comment]
Thanks. This is now in version 1.1.4.
