### ISSUE TITLE
Save doesn't commit changes to filters

### ISSUE THREAD

**Issue by emyoulation** [kkujansuu/gramps#32]
After making changes to the parameters of a Custom Person Filter, I clicked the Save button. 

The changes do not seem to be committed.

After closing FilterParams, I tried "Find" using in the Filter Gramplet and it matched against the original Parameter

Tried again but just switched to another Custom Filter in the FilterParams dialog and back.  It reverted to the original Parameter 

(Could I have disconnected the function from the button when tweaking that Glade file. I'm using the most recent repository version... without additional Glade changes.)

**Comment by emyoulation** [comment]
With the captured custom filter active in the Fan Chart's Filter+ gramplet: 
1) tried tweaking (increase by 1) the Number of generations in Filter Params, clicked Save, clicked Find in Filter+. The results were not changed and using Edit in Custom Filter shows that the Parameter change was not committed.
2) tried the same tweak using Edit in Filter Params, clicked Save, clicked Find in Filter+. The results were not changed and using Edit in Custom Filter shows that the Parameter change was not committed.

Switched the active Custom Filter in Fan Chart's Filter+ gramplet: 
  Repeated the same tests (but switching Filter+ back to the Saved filter before the "Find") with the same results.

![image](https://github.com/user-attachments/assets/3c0fbbc3-89d5-481c-baab-818a53bda3ec)

**Comment by kkujansuu** [comment]
Fixed. Hopefully.

**Comment by emyoulation** [comment]
Nice!  Works nicely on Gramps 5.2.1 on Fedora!

Please update FilterParams revision from 1.1.6
