### ISSUE TITLE
Add-multiple events

### ISSUE THREAD

**Issue by emyoulation** [kkujansuu/gramps#34]
The interface entry point in the Quick View contextual submenu of the Edit Family dialog is not the best place for a Tool.  The Edit Person context menu has an example of inserting 2 menu items able that submenu.

![image](https://github.com/kkujansuu/gramps/assets/69127217/f43ce36e-3214-40f6-8054-0b44ea4ce08d)

**Comment by kkujansuu** [comment]
Yes, but as far as I can see there is no way to add items to the context menu with a plugin.
