### ISSUE TITLE
Add multiple events needs Plugin Registration to differentiate between Person and Family versions

### ISSUE THREAD

**Issue by emyoulation** [kkujansuu/gramps#44]
`Add multiple events` is the `name` and `description` for both the Person and Family quick view.  Please differentiate them.

Here are some suggestions: 

## Family:
https://github.com/kkujansuu/gramps/blob/bafdd0a64fc4654eb31a420e23e107ba5c2d820a/addons/add-multiple-events/add-multiple-events.gpr.py#L34
`    name = _("Add multiple events"),`  original
`    name = _("Add events to Family members"),`  suggested

https://github.com/kkujansuu/gramps/blob/bafdd0a64fc4654eb31a420e23e107ba5c2d820a/addons/add-multiple-events/add-multiple-events.gpr.py#L35
`    description = _("Add multiple events"),`  original
`    description = _("Add or share events to members of a Family"),`  suggested

## Person:
https://github.com/kkujansuu/gramps/blob/bafdd0a64fc4654eb31a420e23e107ba5c2d820a/addons/add-multiple-events/add-multiple-events.gpr.py#L47
`    name = _("Add multiple events"),`  original
`    name = _("Add events to extended Family"),`  suggested

https://github.com/kkujansuu/gramps/blob/bafdd0a64fc4654eb31a420e23e107ba5c2d820a/addons/add-multiple-events/add-multiple-events.gpr.py#L48
`    description = _("Add multiple events"),`  original
`    description = _("Add or share events to a Person and their spouses, children, parents"),`  suggested

**Comment by kkujansuu** [comment]
Done in version 1.2.
