### ISSUE TITLE
Scroll bar when the clustered filters exceed monitor realestate 

### ISSUE THREAD

**Issue by DaveSch-gramps** [kkujansuu/gramps#5]
Brian (emyoulation) pointed me to this new tool.

One issue is I opened a filter that relies on three sub-filters and the window exceeded my monitor screen height. Without a scroll bar there was no way to view the bottom information.

hyvää työtä

**Comment by kkujansuu** [comment]
Yes, I have to add the scroll bars.

**Comment by kkujansuu** [comment]
I think I have fixed this now..
