### ISSUE TITLE
Choosing Edit from the filter tool

### ISSUE THREAD

**Issue by DaveSch-gramps** [kkujansuu/gramps#6]
In seeing what the tool will do, I selected Edit. It bought up the Gramps Define Filter edit window but your FilterParams window closed and to get back the window, have to select the tool, then the filter....

Needs a way way to keep the window open and update any changes made to the rule.

I should have posted that I am on Gramps 5.1.4 on Win10

**Comment by emyoulation** [comment]
The Edit isn't really needed unless you are adding or removing rules from a filter.  If you are refocusing the rules or changing the scope parameters, that isn't necessary.

However, I noted that the FilterParams only incorrectly closes if you hit "Cancel" in the dialog.  Hitting "OK" leaves it open.

**Comment by emyoulation** [comment]
Whoops.  It did not close. the FilterParams window just pushed to behind the main Gramps window and the CLI console!  It lost track in where it should be in the layer of windows.

**Comment by emyoulation** [comment]
See ["Experimental FilterParams add-on, Dark themes and Glade"](![image](https://user-images.githubusercontent.com/69127217/145067875-96286ce9-589e-479f-a58e-6c87230ce430.png)) discussion on Discourse

**Comment by emyoulation** [comment]
Another surprise, when this tool creates a windows, the "Windows" group does not appear in the menu at all. And this window is never listed. Perhaps this is why it loses its position as topmost among the windows associated with Gramps?

**Comment by kkujansuu** [comment]
Perhaps. I have not fully understood how the Gramps "ManagedWindow" class works. Have to investigate more.

**Comment by emyoulation** [comment]
Paul Culley had to wade through a lot of crap to work out some Windoze layering issues with the Clipboard. And Christopher Horn just did some tweaks in the last week to make his add-on (LinkedView, a Relationships view mode) play within the MangledWindows rules.

Maybe engaging them in this conversation would let you avoid some false starts?

**Comment by kkujansuu** [comment]
I think I have fixed this now. Thanks everybody.
