### ISSUE TITLE
Required Gtk version!

### ISSUE THREAD

**Issue by prculley** [kkujansuu/gramps#8]
https://github.com/kkujansuu/gramps/blob/cb30f9ba40b547a8ab7de3134c334e678ae2ae80/addons/FilterParams/filterparams.glade#L4

Gramps is supposed to work with any version of Gtk from 3.12 up.  So you should modify your glade file to work with earlier versions.

**Comment by emyoulation** [comment]
See ["Experimental FilterParams add-on, Dark themes and Glade"](https://gramps.discourse.group/t/experimental-filterparams-add-on-dark-themes-and-glade/2020) discussion on Discourse

**Comment by kkujansuu** [comment]
Done.
