### ISSUE TITLE
Foreground & background colors need to be Dark theme compatible

### ISSUE THREAD

**Issue by emyoulation** [kkujansuu/gramps#9]
Colors for foreground text and backgrounds conflict when Dark Themes are selected.
See [Experimental FilterParams add-on, Dark themes and Glade; Post 5](https://gramps.discourse.group/t/experimental-filterparams-add-on-dark-themes-and-glade/2020/5):
![image](https://user-images.githubusercontent.com/69127217/145069593-4d55926b-7423-4440-9d05-33429cc93233.png)

Chris Horn's experimental [LinkedView Relationships view mode add-on](https://github.com/cdhorn/LinkedView) has been adjusted for more color than most Gramps GUIs and adapted to Light/Dark theme switching.  The Configuration interface is not necessary for a Tools like it is for a view mode, but perhaps the source will give a lead for using color palettes that work with the Theming.
![image](https://user-images.githubusercontent.com/69127217/145070892-fbd2eb53-a8cd-43aa-9136-f5bdb6630774.png)

**Comment by emyoulation** [comment]
Did not care for the [equally unpleasant colors for Light&Dark modes that Dave found ](https://gramps.discourse.group/t/modifying-themes/1938/12) last December. So I've been letting the color selection problem "percolate" for a while. Finally got back to it today.

I tried leveraging the alpha channel part of the RGBa system.  Decided the 1st level was too prominent. So bumped that first level down from a color highlight to a brightness change highlight. Also re-ordered the colors according to the how they are arranged on a color wheel.

The alpha channel works well for both Light & dark themes. It should probably survive other CSS incarnations. And the highlighting seems a bit more subtle to me.

![image](https://user-images.githubusercontent.com/69127217/190716390-c4474f08-b7e0-443a-bf6e-d242f5a8739e.png)
  ![image](https://user-images.githubusercontent.com/69127217/190716298-6cf6786f-db81-4411-81e9-37fb77a92d25.png)

modified [Line 138](https://github.com/kkujansuu/gramps/blob/master/addons/FilterParams/FilterParams.py#L138) as follows:
```
        self.categories_translated = [_(cat) for cat in self.categories]
        self.colors = [
             Gdk.RGBA(0.75,0.75,0.75, 0.250),
             Gdk.RGBA(0.75,0.75,0.99, 0.250),
             Gdk.RGBA(0.75,0.99,0.99, 0.250),
             Gdk.RGBA(0.75,0.99,0.75, 0.250),
             Gdk.RGBA(0.99,0.99,0.75, 0.250),
             Gdk.RGBA(0.99,0.75,0.75, 0.250),
             Gdk.RGBA(0.99,0.75,0.99, 0.250),
        ]
```

GUI screen captures generated with the following `custom_filters.xml` chunk  :
```
<?xml version="1.0" encoding="utf-8"?>
<filters>
  <object type="Person">
    <filter name="Persons at Events in Place X" function="and" comment="Who was at any Event in a Place">
      <rule class="MatchesEventFilter" use_regex="False">
        <arg value="MatchesEventFilter"/>
      </rule>
    </filter>
  </object>
  <object type="Place">
    <filter name="IsEnclosedBy" function="and" comment="Places enclosed">
      <rule class="IsEnclosedBy" use_regex="False">
        <arg value="P0003"/>
        <arg value="0"/>
      </rule>
    </filter>
    <filter name="MatchesPlaceFilter" function="and">
      <rule class="MatchesFilter" use_regex="False">
        <arg value="IsEnclosedBy"/>
      </rule>
    </filter>
  </object>
  <object type="Event">
    <filter name="MatchesEventFilter" function="and" comment="Events in a Place">
      <rule class="MatchesPlaceFilter" use_regex="False">
        <arg value="IsEnclosedBy"/>
      </rule>
    </filter>
  </object>
</filters>
```
Although for a FULL illustration, this Custom Filter probably ought to include multi-rule as well as the 4 level multi-stage.  Maybe add an Active Person or Home Person rule? 
![image](https://user-images.githubusercontent.com/69127217/190721850-1e18b5b6-ca17-4dad-b470-6e444f62a0ee.png)

Well THAT would NOT work.  Forgot to set the multi-rule to "At least one rule" instead of "all rules"
![image](https://user-images.githubusercontent.com/69127217/190729017-8911ef62-1ac0-4924-ae20-37aa243ce462.png)

**Comment by kkujansuu** [comment]
Thanks very much!

**Comment by emyoulation** [comment]
I don't know if my having increased the self.colors array from 6 to 7 makes a difference/problem elsewhere? (Perhaps it will be a problem if a multi-stage Custom Filter goes so deep as to have to start again?)

**Comment by kkujansuu** [comment]
i have now updated the colors as you suggested. Change is in version 1.1.0.

**Comment by emyoulation** [comment]
works in v.1.1.0 version. (thank you) 

Please close
